### ISSUE TITLE
Fargate

### ISSUE THREAD

**Issue by steverecio** [awslabs/ecs-nginx-reverse-proxy#1]
Is this supported on Fargate? I get the error `Fargate only supports network mode ‘awsvpc’`

**Comment by sadams** [comment]
@steverecio i'm just hitting this issue (name of one container isn't resolving as a host in the other container) when using fargate with `awsvpc`. Did you manage to find the solution?

**Comment by mmeylan** [comment]
@steverecio @sadams How have you solved this issue ?
